### ISSUE TITLE
v1.2.x does not work with native Node.js ESM

### ISSUE THREAD

**Issue by hbarcelos** [dankogai/js-combinatorics#68]
If I run the following code snippet:

```js
import { Combination } from "js-combinatorics";

const allPossible = new Combination(["en", "es", "pt", "fr", "tr"], 2);

console.log([...allPossible]);
```

I get the following error:

```
import { Combination } from 'js-combinatorics';
         ^^^^^^^^^^^
SyntaxError: The requested module 'js-combinatorics' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'js-combinatorics';
const { Combination } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:162:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

Looks like the `package.json` of version `1.2.1` is missing the required `"type": "module"` config in order to work properly with Node.js >=13.

Currenlty I get the following `package.json` after installing:

```json
{
  "name": "js-combinatorics",
  "version": "1.2.1",
  "description": "Simple combinatorics like power set, combination, and permutation in JavaScript",
  "main": "combinatorics.js",
  "module": "combinatorics.js",
  "types": "combinatorics.d.ts",
  "files": [
    "combinatorics.d.ts",
    "combinatorics.js"
  ],
  "runkitExample": "require=require(\"esm\")(module);\nvar Combinatorics=require(\"js-combinatorics\");\n",
  "devDependencies": {
    "typescript": "^3.9.7",
    "@types/node": "^14.0.26",
    "mocha": "^8.0.0",
    "chai": "^4.2.0"
  },
  "scripts": {
    "test": "make test"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/dankogai/js-combinatorics.git"
  },
  "keywords": [
    "Combinatorics",
    "combination",
    "permutation"
  ],
  "author": "Dan Kogai",
  "license": "MIT",
  "readmeFilename": "README.md",
  "gitHead": "e3684eb54f7c6fbb24bb7a4d08d88671ce12e9eb"
}
```

If I change the `package.json` for `js-combinatorics` inside `node_modules` like this:

```diff
{
  "name": "js-combinatorics",
  "version": "1.2.1",
+ "type": "module",
  "description": "Simple combinatorics like power set, combination, and permutation in JavaScript",
  "main": "combinatorics.js",
  "module": "combinatorics.js",
  "types": "combinatorics.d.ts",
```

Then the snippet above executes as expected.

## Environment info

- `node.js@14.6.0`
- `js-combinatorics@1.2.1`

**Comment by dankogai** [comment]
Your solution is tempting but I declined to add ` "type": "module"` to 'package.json' for now.

* It is already documented to use [babel] or [esm] on node.

[babel]: https://babeljs.io
[esm]: https://github.com/standard-things/esm

* native module is too hard to use w/ REPL, which is the primary reason.  The following is on [native-node-module].

[native-node-module]: https://github.com/dankogai/js-combinatorics/tree/native-node-module

```
% node
Welcome to Node.js v14.5.0.
Type ".help" for more information.
> import * as $C from './combinatorics.js'
import * as $C from './combinatorics.js'
^^^^^^

Uncaught SyntaxError: Cannot use import statement outside a module
> 
```

```
> var $C = await import('./combinatorics.js')
var $C = await import('./combinatorics.js')
         ^^^^^

Uncaught SyntaxError: await is only valid in async function
```

```
> import('./combinatorics.js').then(m=>$C=m)
Promise { <pending> }
> (node:28213) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

> $C
[Module] {
  BaseN: [class BaseN extends _CBase],
  CartesianProduct: [class CartesianProduct extends _CBase],
  Combination: [class Combination extends _CBase],
  Permutation: [class Permutation extends _CBase],
  PowerSet: [class PowerSet extends _CBase],
  combination: [Function: combination],
  factoradic: [Function: factoradic],
  factorial: [Function: factorial],
  permutation: [Function: permutation],
  version: '1.2.1'
}
```

With [esm] it is as casual as (now back to [master]):

[master]: https://github.com/dankogai/js-combinatorics/tree/master

```
% node -r esm
Welcome to Node.js v14.5.0.
Type ".help" for more information.
> import * as $C from './combinatorics.js'
undefined
> $C
[Module] {
  BaseN: [Function: BaseN],
  CartesianProduct: [Function: CartesianProduct],
  Combination: [Function: Combination],
  Permutation: [Function: Permutation],
  PowerSet: [Function: PowerSet],
  combination: [Function: combination],
  factoradic: [Function: factoradic],
  factorial: [Function: factorial],
  permutation: [Function: permutation],
  version: '1.2.1'
}
> 
```

**Comment by papandreou** [comment]
Using esm in my node.js project is unfortunately not an option, as it pretty much amounts to adding a transpiler. Would you be opposed to add a UMD or common.js build to the published package?

**Comment by dankogai** [comment]
I've added `umd` and `commonjs` to `make` target so you can

```shell
$ make umd
```

to get umd version of `combinatorics.js` (and `make commonjs` to commonjs version).  all it does is

```shell
$ tsc --module umd --target es6 combinatorics.ts
```

This is the furthest compromise I can make because I am pro-module.  Also note you still need ES6 features.

**Comment by papandreou** [comment]
Thanks for that! How about renaming those built files to `combinatorics-commonjs.js` and `combinatorics-umd.js` respectively and including them in the published package? That way I can deep-`require` the version I need.

I'm not asking you to change the `main` of the package or anything, just to give me a way to get those legacy builds without forking the package or checking the build artifacts into my own tree.

I'm happy to open a PR if the above sounds OK?

I think we're all pro-module, but it's still very early days wrt. switching over a big node.js-based project. I hope to be able to make the jump soon, though :)

**Comment by dankogai** [comment]
Sounds fair.  I'll wait for your PR.
