### ISSUE TITLE
Move to ES6 breaks node compatability

### ISSUE THREAD

**Issue by markflare** [dankogai/js-combinatorics#72]
I took the following steps:
* Install js-combinator version 1.4.3
* Create test.js:
`const c = require('js-combinatorics');`
* Run `node test.js`

Error:

```
export const version = '1.4.3';
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/private/tmp/combinatrics-test/test.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
```

Is the expectation that for node the `version0` branch is used?

**Comment by dankogai** [comment]
It is deliberate and explicitly documented.

https://github.com/dankogai/js-combinatorics#commonjs-nodejs

**Comment by markflare** [comment]
I appreciate it's deliberate, however babel / esm is not always going to be a solution for all environments. Will the `version0` branch be ongoingly available in these cases?

**Comment by dankogai** [comment]
> `./combinatorics.js` is an ECMAScript module but if you still need a UMD or commonjs version, they are available as `./umd/combinatorics.js` and `./commonjs/combinatorics.js` respectively.

**Comment by markflare** [comment]
Thanks
